version: 2
jobs:
  build:
    working_directory: ~/decide
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres
      - image: circleci/postgres:9.6-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: decide_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "Gemfile.lock" }}
            - v1-dep-bundle-
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v1-dep-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: bundle exec rspec --color --format documentation --require spec_helper --require rails_helper spec
          environment:
            RAILS_GROUPS: assets
      - store_artifacts:
          path: coverage
          prefix: tests
      - run: ./scripts/verify_updated_documentation.sh
workflows:
  version: 2
  build:
    jobs:
      - build